### ISSUE TITLE
compatible with what latest gcc version?

### ISSUE THREAD

**Issue by KjellKod** [fredericgermain/LeakTracer#8]
Hi, 

What version of gcc is LeakTracer compatible with?  When running it against programs compiled with gcc 4.8.2 I see the following warnings during the analyzing step

(copying example warnings)
```
During symbol reading, unsupported tag: 'DW_TAG_GNU_template_parameter_pack'.
During symbol reading, unexpected tag in read_type_die: 'DW_TAG_rvalue_reference_type'.
During symbol reading, cannot get low and high bounds for subprogram DIE at 568036.
```

**Comment by fredericgermain** [comment]
it should work on many versions. I tried on GCCs from 6 years ago, and I recently tried on something like gcc 6.4.1 on fedora 25.

Please make gcc/gdb comes from the same toolchain though. The GNU toolchain usually consists of these 3 sources packages : 
- binutils
- gcc
- gdb

**Comment by KjellKod** [comment]
I rebuilt it with the `rpath` etc set for our toolchain but didn't see a difference. 
If I get time to look into it some more I'll.   I'll close this for now since no information came up that is helpful or that could explain it.
